language: java
install: true

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - build

before_script:
  - if [ -n "$TRAVIS_TAG" ]; then
    export USE_CI_VERSION="true";
    export CI_VERSION=$TRAVIS_TAG;
    else
    export USE_CI_VERSION="false";
    fi

stages:
  - name: Test
    if: NOT env(TRAVIS_EVENT_TYPE) = cron
  - Analysis
  - name: Release
    if: tag IS present AND NOT env(TRAVIS_EVENT_TYPE) = cron

jobs:
  include:
    - stage: Test
      name: Tests and Coverage
      script: ./gradlew jacocoCoverageReport jacocoTestReport jacocoTestCoverageVerification printCoverage -x checkstyleMain -x checkstyleTest
    - stage: Analysis
      name: Code Verification
      if: tag IS blank AND NOT env(TRAVIS_EVENT_TYPE) = cron
      script: ./gradlew checkstyleMain
    - stage: Analysis
      name: Sonarqube
      if: branch = master AND NOT type = pull_request AND NOT env(TRAVIS_EVENT_TYPE) = cron
      script: ./gradlew sonarqube -x test
    - stage: Analysis
      name: Gradle Dependency Updates
      if: env(TRAVIS_EVENT_TYPE) = cron
      script: ./gradlew createGithubIssue
    - stage: Release
      name: Publish to Gradle
      script: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
