---
name: Release

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ 11 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '${{  matrix.java-version }}'

      - name: Tests and Coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoCoverageReport jacocoTestReport jacocoTestCoverageVerification printCoverage -x checkstyleMain -x checkstyleTest

      - name: Checkstyle Analysis
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyleMain

  release:
    runs-on: ubuntu-latest
    name: Release
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ 11 ]
    needs:
      - verify

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.GH_PUSH_TOKEN }}'
      - uses: actions/setup-java@v1
        with:
          java-version: '${{  matrix.java-version }}'
      - name: Setup Git
        run: |
          git config --local user.email "${{ env.GITHUB_ACTION }}+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --tags

      - name: Versioning and Changelog
        run: |
          npx standard-version -i release-CHANGELOG.md --skip.commit --skip.tag
          npx standard-version
      - name: Push to Repository
        run: |
          git push --follow-tags
      - name: Get Tag for Release
        run: |
          echo "TAG_NAME=`git describe --abbrev=0 --match "v*"`" >> $GITHUB_ENV

      - name: Publish Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugins -Pgradle.publish.key=${{ env.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ env.GRADLE_PUBLISH_SECRET }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "release-CHANGELOG.md"
          name: '${{ env.TAG_NAME }}'
          tag: '${{ env.TAG_NAME }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
