---
name: Verify

on:
  push:
    branches-ignore:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    strategy:
      max-parallel: 4
      matrix:
        java-version: [ 11 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '${{  matrix.java-version }}'

      - name: Tests and Coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoCoverageReport jacocoTestReport jacocoTestCoverageVerification printCoverage -x checkstyleMain -x checkstyleTest

      - name: Checkstyle Analysis
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyleMain
